"""
Sınav kağıdı üretimi (LaTeX → PDF).

Neden tarayıcıda değil de sunucuda?
Tarayıcının yazdırma penceresi bir web sayfasını kağıda döküyor; çıktı ne
tipografik olarak sınav kağıdına benziyor ne de tek tıkla iniyor. LaTeX ise
matematik dizgisi için yapılmış: formüller, matrisler ve denklem sistemleri
doğru hizalanıyor, çıktı gerçek bir sınav kağıdı gibi duruyor.

Neden modele LaTeX yazdırmıyoruz?
Yazdırıyorduk ve kaldırdık — model aynı içeriği iki kez üretiyordu (bir kez
soru metni, bir kez LaTeX gövdesi) ve çıktı token'ının yarısı çöpe gidiyordu.
Sorular elimizde yapısal veri olarak durduğu için LaTeX'i burada, şablondan
üretmek sıfır token harcıyor.

Kurulum gereksinimi:
  Windows : MiKTeX (https://miktex.org) — eksik paketleri otomatik indiriyor
  Ubuntu  : sudo apt install texlive-latex-recommended texlive-latex-extra
            (tam texlive'a gerek yok, ~2 GB yerine ~500 MB)
"""

from __future__ import annotations

import logging
import re
import shutil
import subprocess
import tempfile
from datetime import date
from pathlib import Path

logger = logging.getLogger(__name__)

# Derleme için üst süre sınırı. pdflatex bir hatada sonsuz bekleyebiliyor;
# nonstopmode bunu çoğunlukla engelliyor ama garanti için timeout şart.
COMPILE_TIMEOUT = 60

# Matematik blokları: $$...$$ veya $...$
# Bunları OLDUĞU GİBİ bırakıyoruz, sadece aralarındaki düz metni kaçırıyoruz.
_MATH_SPLIT = re.compile(r"(\$\$.*?\$\$|\$[^$]*\$)", re.DOTALL)

# LaTeX'te özel anlamı olan karakterler ve düz metindeki karşılıkları.
_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


class LatexNotInstalled(RuntimeError):
    """Sistemde pdflatex bulunamadı."""


class LatexCompileError(RuntimeError):
    """Derleme başarısız oldu."""


def latex_available() -> bool:
    return shutil.which("pdflatex") is not None


def _escape_text(text: str) -> str:
    """
    Matematik DIŞINDAKİ metni LaTeX için güvenli hale getirir.

    Ters bölü önce işleniyor: sonraki değiştirmelerin ürettiği ters bölüleri
    tekrar kaçırmamak için.
    """
    out = text.replace("\\", _ESCAPES["\\"])
    for char, replacement in _ESCAPES.items():
        if char == "\\":
            continue
        out = out.replace(char, replacement)
    return out


def markdown_to_latex(text: str) -> str:
    """
    Soru metnini LaTeX gövdesine çevirir.

    Metin Markdown + LaTeX karışımı geliyor. Matematik zaten LaTeX, dokunmuyoruz;
    etrafındaki düz metni kaçırıyoruz. Kaçırmayı matematiğin içine uygularsak
    $\\det(A)$ ifadesi $\\textbackslash{}det(A)$ olur ve formül bozulur — bu
    yüzden önce matematik bloklarına göre bölüyoruz.
    """
    parts = _MATH_SPLIT.split(text)
    rendered: list[str] = []

    for index, part in enumerate(parts):
        # split, yakalama grubu sayesinde matematik parçalarını tek sayılı
        # indekslere koyuyor.
        if index % 2 == 1:
            # $$...$$ → \[...\]: LaTeX'te blok matematiğin doğru biçimi.
            if part.startswith("$$"):
                inner = part[2:-2].strip()
                rendered.append(f"\n\\[\n{inner}\n\\]\n")
            else:
                rendered.append(part)
            continue

        escaped = _escape_text(part)
        # **kalın** → \textbf{}
        escaped = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", escaped)
        # Tek satır sonu = satır başı (şıklar alt alta dursun),
        # çift satır sonu = paragraf.
        escaped = escaped.replace("\n\n", "\\par ")
        escaped = escaped.replace("\n", " \\\\ ")
        rendered.append(escaped)

    body = "".join(rendered)
    # Blok matematiğin hemen öncesindeki satır sonu LaTeX'i kızdırıyor
    # ("There's no line here to end").
    body = re.sub(r"\\\\\s*(\n?\\\[)", r"\1", body)
    body = re.sub(r"\\par\s*(\n?\\\[)", r"\1", body)
    return body.strip()


DOCUMENT_TEMPLATE = r"""\documentclass[11pt,a4paper]{article}

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage[margin=2.2cm]{geometry}
\usepackage{enumitem}
\usepackage{fancyhdr}
\usepackage{graphicx}

\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\small COURSE}
\fancyhead[R]{\small EXAMTYPE}
\fancyfoot[C]{\small \thepage}
\renewcommand{\headrulewidth}{0.4pt}

\setlength{\parindent}{0pt}

\begin{document}

\begin{center}
    {\Large \textbf{COURSE}}\\[0.3em]
    {\large EXAMTYPE}\\[0.6em]
    {\small QUESTIONCOUNT questions \quad\textbullet\quad DATE}
\end{center}

\vspace{0.4em}
\hrule
\vspace{1.2em}

BODY

\vfill
\begin{center}
    {\footnotesize Generated by BRANDNAME from past exam papers}
\end{center}

\end{document}
"""


def build_exam_tex(
    questions: list[str],
    *,
    course: str,
    exam_type: str,
    answer_space: str = "3cm",
    figures: dict[int, str] | None = None,
) -> str:
    """
    Soru listesinden tam bir LaTeX belgesi kurar.

    answer_space: her sorunun altında bırakılan cevap boşluğu. Kağıda basıp
    çözecek öğrenci için; ekranda okuyacaksa küçültülebilir.

    figures: soru indeksi → görsel dosya adı. Şekilli bir soruyu şekilsiz
    basmak onu cevaplanamaz hale getiriyor: devre şeması olmadan devre sorusu,
    bölge olmadan alan sorusu anlamsız.
    """
    figures = figures or {}
    items = []

    for index, question in enumerate(questions):
        body_text = ""

        if index in figures:
            # Şekil metnin ÜSTÜNDE: sınav kağıtlarında yerleşim böyle,
            # öğrenci önce şekle bakıp sonra ne istendiğini okuyor.
            #
            # Genişlik satırın %70'i: daha büyüğü sayfayı tek soruya ayırıyor,
            # daha küçüğü okunmuyor.
            body_text += (
                "\\begin{center}\n"
                f"\\includegraphics[width=0.7\\linewidth]{{{figures[index]}}}\n"
                "\\end{center}\n\n"
            )

        body_text += markdown_to_latex(question)

        items.append(
            "\\item\n" + body_text + f"\n\\vspace{{{answer_space}}}\n"
        )

    body = (
        "\\begin{enumerate}[leftmargin=*, itemsep=1.2em]\n"
        + "\n".join(items)
        + "\n\\end{enumerate}"
    )

    # Basit yer tutucu değişimi. Jinja kullanmıyoruz: LaTeX'in kendi süslü
    # parantezleri Jinja sözdizimiyle çakışıyor ve özel ayraç tanımlamak
    # gerekiyor — bu boyutta belge için gereksiz karmaşa.
    from app.config import get_settings

    return (
        DOCUMENT_TEMPLATE.replace("BRANDNAME", _escape_text(get_settings().brand_name))
        .replace("COURSE", _escape_text(course))
        .replace("EXAMTYPE", _escape_text(exam_type))
        .replace("QUESTIONCOUNT", str(len(questions)))
        .replace("DATE", date.today().strftime("%d.%m.%Y"))
        .replace("BODY", body)
    )


def compile_pdf(tex_source: str, assets: dict[str, bytes] | None = None) -> bytes:
    """
    LaTeX kaynağını derleyip PDF baytlarını döndürür.

    assets: derleme klasörüne yazılacak yardımcı dosyalar (görseller).
    pdflatex görselleri diskten okuyor; bayt olarak veremiyoruz.

    Geçici klasörde çalışıyoruz: eşzamanlı isteklerde aynı dosya adına yazma
    çakışması olmasın ve ara dosyalar (.aux, .log) diskte birikmesin.
    """
    if not latex_available():
        raise LatexNotInstalled(
            "pdflatex bulunamadı. Windows: MiKTeX kur. "
            "Ubuntu: sudo apt install texlive-latex-recommended texlive-latex-extra"
        )

    with tempfile.TemporaryDirectory() as workdir:
        tex_path = Path(workdir) / "exam.tex"
        tex_path.write_text(tex_source, encoding="utf-8")

        for name, data in (assets or {}).items():
            # Dosya adını biz üretiyoruz ama yine de yol ayracı temizliyoruz:
            # ".." içeren bir ad geçici klasörün dışına yazabilirdi.
            (Path(workdir) / Path(name).name).write_bytes(data)

        result = subprocess.run(
            [
                "pdflatex",
                "-interaction=nonstopmode",
                "-halt-on-error",
                "-output-directory",
                workdir,
                str(tex_path),
            ],
            capture_output=True,
            timeout=COMPILE_TIMEOUT,
            text=True,
            errors="replace",
        )

        pdf_path = Path(workdir) / "exam.pdf"
        if not pdf_path.exists():
            # pdflatex'in çıktısı çok uzun; hata satırlarını süzüyoruz.
            errors = [
                line
                for line in result.stdout.splitlines()
                if line.startswith("!") or "Error" in line
            ]
            logger.error("LaTeX derleme hatası: %s", errors[:5])
            raise LatexCompileError(
                "PDF derlenemedi. " + (errors[0] if errors else "Bilinmeyen hata.")
            )

        return pdf_path.read_bytes()